package com.serrano.dictproject.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xff005e80)
val md_theme_light_onPrimary = Color(0xffffffff)
val md_theme_light_primaryContainer = Color(0xff80ddff)
val md_theme_light_onPrimaryContainer = Color(0xff002533)
val md_theme_light_secondary = Color(0xff334d4d)
val md_theme_light_onSecondary = Color(0xffffffff)
val md_theme_light_secondaryContainer = Color(0xffb3cccc)
val md_theme_light_onSecondaryContainer = Color(0xff141f1f)
val md_theme_light_tertiary = Color(0xff202060)
val md_theme_light_onTertiary = Color(0xffffffff)
val md_theme_light_tertiaryContainer = Color(0xff9f9fdf)
val md_theme_light_onTertiaryContainer = Color(0xff0d0d26)
val md_theme_light_surface = Color(0xffffffff)
val md_theme_light_onSurface = Color(0xff000000)
val md_theme_light_surfaceVariant = Color(0xff1f1f1f)
val md_theme_light_onSurfaceVariant = Color(0xffcccccc)
val md_theme_light_error = Color(0xff800000)
val md_theme_light_onError = Color(0xffffffff)
val md_theme_light_background = Color(0xffffffff)
val md_theme_light_onBackground = Color(0xff000000)

val md_theme_dark_primary = Color(0xffffffff)
val md_theme_dark_onPrimary = Color(0xff005e80)
val md_theme_dark_primaryContainer = Color(0xff002533)
val md_theme_dark_onPrimaryContainer = Color(0xff80ddff)
val md_theme_dark_secondary = Color(0xffffffff)
val md_theme_dark_onSecondary = Color(0xff334d4d)
val md_theme_dark_secondaryContainer = Color(0xff141f1f)
val md_theme_dark_onSecondaryContainer = Color(0xffb3cccc)
val md_theme_dark_tertiary = Color(0xffffffff)
val md_theme_dark_onTertiary = Color(0xff202060)
val md_theme_dark_tertiaryContainer = Color(0xff0d0d26)
val md_theme_dark_onTertiaryContainer = Color(0xff9f9fdf)
val md_theme_dark_surface = Color(0xff000000)
val md_theme_dark_onSurface = Color(0xffffffff)
val md_theme_dark_surfaceVariant = Color(0xffcccccc)
val md_theme_dark_onSurfaceVariant = Color(0xff1f1f1f)
val md_theme_dark_error = Color(0xffffffff)
val md_theme_dark_onError = Color(0xff800000)
val md_theme_dark_background = Color(0xff000000)
val md_theme_dark_onBackground = Color(0xffffffff)